unzip("C:/Users/antop/Documents/R/ExploratoryDataAnalysis1/exdata_data_household_power_consumption.zip")
dt <- read.table("C:/Users/antop/Documents/R/ExploratoryDataAnalysis1/household_power_consumption.txt", header =TRUE, sep=";", na.strings="?")
data <- subset(dt, dt$Date %in% c("1/2/2007", "2/2/2007"))
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
datetime <- paste(data$Date, data$Time)
data$datetime <- as.POSIXct(datetime)
png("plot2.png", width=480, height = 480)
plot(data$Global_active_power ~ data$datetime, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.off()
